### ISSUE TITLE
Dudas con la clase Reenvio

### ISSUE THREAD

**Issue by Sofia-cd** [UDC-FIC-VVS/sistema-de-correo-electronico-Sofia-cd#3]
@lauramcastro 
¿Sería correcto poder crear un reenvio que reenviase una carpeta?

**Comment by lauramcastro** [comment]
Non, a especificación di explicitamente que **un reenvío é unha Mensaxe** (non un Correo). Por iso existe a clase MensaxeAbstracto, que é irmá de Carpeta (e especialización de CorreoAbstracto)
