### ISSUE TITLE
Duda a la hora de hacer Pruebas de Unidad manualmente

### ISSUE THREAD

**Issue by Sofia-cd** [UDC-FIC-VVS/sistema-de-correo-electronico-Sofia-cd#4]
@lauramcastro 

Esta duda me surgió a la hora de hacer las pruebas para diferentes clases, un caso es el test de la clase CarpetaLimitada.

1- Cuando quiero hacer un test del método añadir me encuentro con el problema de que no puedo acceder directamente al vector de la clase porque es privado. Entonces, lo que compruebo, es si el padre del mensaje es la carpeta en la que lo añado. Pero, realmente, puede que se establezca bien el padre pero que no se esté incluyendo el mensaje en el vector de la carpeta. No sé si estaría bien utilizar el método explorar, de la misma clase, para recuperar el vector y ver si el mensaje está contenido en él, o, si eso crearía dependencia entre los tests.

2- Otra duda es en la prueba del método obtener visualización. El método de obtenerVisualización, de la clase CarpetaLimitada, delega en el mismo método de la clase carpeta. ¿Está bien hacer un assert que simplemente compruebe que lo que devuelve este método, de la clase carpetaLimitada, sea lo mismo que lo que devuelve el método de la clase carpeta? ¿O sería mejor que crease yo el string resultante y obviase la llamada a la clase carpeta?

**Comment by Sofia-cd** [comment]
@lauramcastro 
Tengo un problema similar al primero en el test de la clase ArchivadorSimple cuando pruebo el método almacenarCorreo. Si el vector es privado y no tengo un método que devuelva el vector, ¿Cómo compruebo que se ha añadido el correo correctamente?

**Comment by lauramcastro** [comment]
Respecto á segunda dúbida, é mellor que crees a cadea agardada: en caso de que a implementación cambiase e deixase de delegar, a proba deixaría de ser válida se usas agora o "coñecemento" de que se está delegando simplemente.

En relación á primeira dúbida, efectivamente, non podes acceder ao atributo, polo que tes que comprobar que a operación ten o efecto desexado de xeito indirecto. Usar para iso o método _explorar_ é unha opción axeitada.
