### ISSUE TITLE
Propiedades

### ISSUE THREAD

**Issue by Sofia-cd** [UDC-FIC-VVS/sistema-de-correo-electronico-Sofia-cd#5]
@lauramcastro Para las pruebas relativas a las clases audio, imagen y texto debería crear generadores de estas clases o es correcto como hago ahora, pasarle a las propiedades los strings y y que sea la propiedad la que cree la clase audio, imagen...

**Comment by lauramcastro** [comment]
Tal e como o tes, "vale", é dicir, "fai o traballo" e funciona. Agora ben, se es quen de crear clases xeradoras dos tipos de datos de negocio (isto é, xeradores de Textos, xeradores de Audios, etc.) o código de probas será máis mantible, xa que no caso de que unha desas clases cambie e por exemplo teña un atributo novo, só tes que cambiar esa clase xeradora, e non todas as propiedades onde precisas ese obxecto.
